#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Command-line entry point and compatibility imports for calibration.

Implementation functions live in calibration_functions/<function_name>.py.
Import interfaces with ``from Calibration import run_dfc_mesh``.
See README.md for the file map and direct-import examples.
"""

from __future__ import annotations

# Explicit imports retain both public functions and existing private helpers.
from calibration_functions._env_bool import _env_bool
from calibration_functions.log import log
from calibration_functions.log_section import log_section
from calibration_functions.log_kv import log_kv
from calibration_functions._setup_output_capture import _setup_output_capture
from calibration_functions._discover_paper_root_dir import _discover_paper_root_dir
from calibration_functions.paper_profile import paper_profile
from calibration_functions.apply_paper_profile import apply_paper_profile
from calibration_functions.pick_ring_result import pick_ring_result
from calibration_functions._jsonable import _jsonable
from calibration_functions._write_json import _write_json
from calibration_functions._write_csv import _write_csv
from calibration_functions._git_commit_hash import _git_commit_hash
from calibration_functions._next_pow2 import _next_pow2
from calibration_functions.balanced_kway_hypergraph_partition import balanced_kway_hypergraph_partition
from calibration_functions._kahypar_partition import _kahypar_partition
from calibration_functions._mtkahypar_initializer import _mtkahypar_initializer
from calibration_functions._mtkahypar_preset import _mtkahypar_preset
from calibration_functions._mtkahypar_partition import _mtkahypar_partition
from calibration_functions.partition_hypergraph import partition_hypergraph
from calibration_functions._hadamard import _hadamard
from calibration_functions._orthogonal_sign_patterns import _orthogonal_sign_patterns
from calibration_functions._default_cross_terms import _default_cross_terms
from calibration_functions.cross_terms_from_internal_edges import cross_terms_from_internal_edges
from calibration_functions.fit_surrogate_with_trust_region import fit_surrogate_with_trust_region
from calibration_functions._solve_qp_docplex import _solve_qp_docplex
from calibration_functions.gauss_newton_solve import gauss_newton_solve
from calibration_functions._resolve_step_solver import _resolve_step_solver
from calibration_functions._jacobian_condition_number import _jacobian_condition_number
from calibration_functions.build_toy_mesh_hypergraph import build_toy_mesh_hypergraph
from calibration_functions.build_toy_mesh_plant import build_toy_mesh_plant
from calibration_functions._xlsx_cell import _xlsx_cell
from calibration_functions._write_xlsx import _write_xlsx
from calibration_functions._seed_everything import _seed_everything
from calibration_functions.summarize_effort import summarize_effort
from calibration_functions._parse_method_list import _parse_method_list
from calibration_functions._expand_token_list import _expand_token_list
from calibration_functions.expand_sweep_spec import expand_sweep_spec
from calibration_functions.apply_sweep_overrides import apply_sweep_overrides
from calibration_functions._partition_with_solver_metadata import _partition_with_solver_metadata
from calibration_functions._resolve_opt_solver_used import _resolve_opt_solver_used
from calibration_functions.run_dfc_mesh import run_dfc_mesh
from calibration_functions.run_mesh_global_surrogate import run_mesh_global_surrogate
from calibration_functions.run_mesh_tune_and_check import run_mesh_tune_and_check
from calibration_functions._ring_metrics_from_trace import _ring_metrics_from_trace
from calibration_functions._standardize_ring_trace import _standardize_ring_trace
from calibration_functions._ring_cross_talk_matrix import _ring_cross_talk_matrix
from calibration_functions.build_ring_hypergraph import build_ring_hypergraph
from calibration_functions._cross_talk_sweep_values import _cross_talk_sweep_values
from calibration_functions.simulate_ring_bank import simulate_ring_bank
from calibration_functions.simulate_ring_scan import simulate_ring_scan
from calibration_functions._mesh_trace_rows_for_xlsx import _mesh_trace_rows_for_xlsx
from calibration_functions._append_ring_trace_rows import _append_ring_trace_rows
from calibration_functions._mesh_row_from_result import _mesh_row_from_result
from calibration_functions._ring_row_from_result import _ring_row_from_result
from calibration_functions._paper_mesh_strategy_and_k import _paper_mesh_strategy_and_k
from calibration_functions._paper_mesh_rows import _paper_mesh_rows
from calibration_functions._paper_ring_rows import _paper_ring_rows
from calibration_functions._format_sci_tex import _format_sci_tex
from calibration_functions._format_paper_time_s import _format_paper_time_s
from calibration_functions._format_paper_peak_pm import _format_paper_peak_pm
from calibration_functions._format_paper_rms_pm import _format_paper_rms_pm
from calibration_functions._format_paper_settle_ms import _format_paper_settle_ms
from calibration_functions.write_paper_mesh_table import write_paper_mesh_table
from calibration_functions.write_paper_ring_table import write_paper_ring_table
from calibration_functions.write_paper_manifest import write_paper_manifest
from calibration_functions.validate_paper_results import validate_paper_results
from calibration_functions.validate_paper_artifacts import validate_paper_artifacts
from calibration_functions.run_mesh_suite import run_mesh_suite
from calibration_functions.run_ring_suite import run_ring_suite
from calibration_functions._mesh_vertex_positions import _mesh_vertex_positions
from calibration_functions._ring_vertex_positions import _ring_vertex_positions
from calibration_functions._partition_palette import _partition_palette
from calibration_functions._plot_hypergraph import _plot_hypergraph
from calibration_functions.generate_hypergraph_plots import generate_hypergraph_plots
from calibration_functions._extract_mesh_round_series import _extract_mesh_round_series
from calibration_functions._mean_series import _mean_series
from calibration_functions.generate_mesh_outer_round_plots import generate_mesh_outer_round_plots
from calibration_functions._plot_mesh_convergence import _plot_mesh_convergence
from calibration_functions._plot_mesh_cut_edge_residuals import _plot_mesh_cut_edge_residuals
from calibration_functions._plot_mesh_jacobian_conditioning import _plot_mesh_jacobian_conditioning
from calibration_functions.generate_mesh_plots import generate_mesh_plots
from calibration_functions.generate_ring_plots import generate_ring_plots
from calibration_functions.write_mesh_table import write_mesh_table
from calibration_functions.write_ring_table import write_ring_table
from calibration_functions.build_arg_parser import build_arg_parser
from calibration_functions.main import main
from calibration_functions.models import TeeStream
from calibration_functions.models import PhysicsParams
from calibration_functions.models import CalibrationConfig
from calibration_functions.models import MetricCounters
from calibration_functions.models import Hyperedge
from calibration_functions.models import Hypergraph
from calibration_functions.models import PartitionResult
from calibration_functions.models import PolyRidgeSurrogate
from calibration_functions.models import SurrogateFitReport
from calibration_functions.models import ToyMeshPlant
from calibration_functions.models import BlockModel
from calibration_functions.models import IncrementalPID
from calibration_functions.settings import PAPER_ROOT_DIR
from calibration_functions.settings import SCRIPT_DIR
from calibration_functions.settings import RESULTS_DIR
from calibration_functions.settings import PAPER_DATA_DIR
from calibration_functions.settings import VERBOSE
from calibration_functions.settings import PROJECT_ROOT_DIR
from calibration_functions.constants import MESH_TRACE_FIELDS
from calibration_functions.constants import RING_ROW_FIELDS
from calibration_functions.constants import MESH_ROW_FIELDS
from calibration_functions.constants import RING_TRACE_SHEETS
from calibration_functions.constants import PAPER_RING_TABLE_FIELDS
from calibration_functions.constants import RING_TRACE_BASE_FIELDS
from calibration_functions.constants import PAPER_MESH_TABLE_FIELDS
from calibration_functions.constants import MESH_TRACE_SHEET_FIELDS
from calibration_functions.constants import RUN_SUMMARY_FIELDS
from calibration_functions._mtkahypar_initializer import _MTK_INITIALIZER


if __name__ == "__main__":
    raise SystemExit(main())
