"""Test runner for CalibrationInvariantTests.

Each test body lives in calibration_test_functions/<test_name>.py.
Run ``python -m unittest -v test_calibration``.
"""

from __future__ import annotations

import unittest

from calibration_test_functions._support import CAL, MODULE_PATH, SPEC
from calibration_test_functions.test_discover_paper_root_dir_prefers_nested_manuscript_folder import test_discover_paper_root_dir_prefers_nested_manuscript_folder as _test_discover_paper_root_dir_prefers_nested_manuscript_folder
from calibration_test_functions.test_paper_profile_locks_requested_camera_ready_fields import test_paper_profile_locks_requested_camera_ready_fields as _test_paper_profile_locks_requested_camera_ready_fields
from calibration_test_functions.test_pick_ring_result_prefers_requested_cross_talk import test_pick_ring_result_prefers_requested_cross_talk as _test_pick_ring_result_prefers_requested_cross_talk
from calibration_test_functions.test_write_ring_table_uses_preferred_cross_talk_and_no_relock_marker import test_write_ring_table_uses_preferred_cross_talk_and_no_relock_marker as _test_write_ring_table_uses_preferred_cross_talk_and_no_relock_marker
from calibration_test_functions.test_tunecheck_probe_invariant import test_tunecheck_probe_invariant as _test_tunecheck_probe_invariant
from calibration_test_functions.test_paper_export_and_manifest_invariants import test_paper_export_and_manifest_invariants as _test_paper_export_and_manifest_invariants
from calibration_test_functions.test_ring_probe_rounds_match_trace_length import test_ring_probe_rounds_match_trace_length as _test_ring_probe_rounds_match_trace_length


class CalibrationInvariantTests(unittest.TestCase):
    """Bind the extracted functions while retaining the test method names."""

    test_discover_paper_root_dir_prefers_nested_manuscript_folder = _test_discover_paper_root_dir_prefers_nested_manuscript_folder
    test_paper_profile_locks_requested_camera_ready_fields = _test_paper_profile_locks_requested_camera_ready_fields
    test_pick_ring_result_prefers_requested_cross_talk = _test_pick_ring_result_prefers_requested_cross_talk
    test_write_ring_table_uses_preferred_cross_talk_and_no_relock_marker = _test_write_ring_table_uses_preferred_cross_talk_and_no_relock_marker
    test_tunecheck_probe_invariant = _test_tunecheck_probe_invariant
    test_paper_export_and_manifest_invariants = _test_paper_export_and_manifest_invariants
    test_ring_probe_rounds_match_trace_length = _test_ring_probe_rounds_match_trace_length


if __name__ == "__main__":
    unittest.main()
